<?php
    /*********************************************************************************
    * By installing or using this file, you are confirming on behalf of the entity
    * subscribed to the SugarCRM Inc. product ("Company") that Company is bound by
    * the SugarCRM Inc. Master Subscription Agreement (“MSA”), which is viewable at:
    * http://www.sugarcrm.com/master-subscription-agreement
    *
    * If Company is not bound by the MSA, then by installing or using this file
    * you are agreeing unconditionally that Company will be bound by the MSA and
    * certifying that you have authority to bind Company accordingly.
    *
    * Copyright (C) 2004-2013 SugarCRM Inc.  All rights reserved.
    ********************************************************************************/

    $dictionary['C_Payments'] = array(
        'table'=>'c_payments',
        'audited'=>true,
        'duplicate_merge'=>true,
        'fields'=>array (
            'name' => 
            array (
                'name' => 'name',
                'vname' => 'LBL_NAME',
                'type' => 'name',
                'link' => true,
                'dbType' => 'varchar',
                'len' => '255',
                'unified_search' => false,
                'full_text_search' => 
                array (
                    'boost' => 3,
                ),
                'required' => false,
                'importable' => 'true',
                'duplicate_merge' => 'enabled',
                'merge_filter' => 'selected',
                'massupdate' => 0,
                'no_default' => false,
                'comments' => '',
                'help' => '',
                'duplicate_merge_dom_value' => '3',
                'audited' => false,
                'reportable' => true,
                'calculated' => false,
                'size' => '20',
            ),
            'payment_amount' => 
            array (
                'required' => true,
                'name' => 'payment_amount',
                'vname' => 'LBL_PAYMENT_AMOUNT',
                'type' => 'currency',
                'massupdate' => 0,
                'no_default' => false,
                'comments' => '',
                'help' => '',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => true,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'len' => 26,
                'size' => '20',
                'enable_range_search' => true,
                'options' => 'numeric_range_search_dom',
                'precision' => 2,
            ),
            'payment_attempt' => 
            array (
                'required' => false,
                'name' => 'payment_attempt',
                'vname' => 'LBL_PAYMENT_ATTEMPT',
                'type' => 'int',
                'dbType' => 'varchar',
                'len' => '5',
                'enable_range_search' => true,
                'options' => 'numeric_range_search_dom',
            ),
            'currency_id' => 
            array (
                'required' => false,
                'name' => 'currency_id',
                'vname' => 'LBL_CURRENCY',
                'type' => 'currency_id',
                'massupdate' => 0,
                'no_default' => false,
                'comments' => '',
                'help' => '',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => 0,
                'audited' => false,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'len' => 36,
                'size' => '20',
                'dbType' => 'id',
                'studio' => 'visible',
                'function' => 
                array (
                    'name' => 'getCurrencyDropDown',
                    'returns' => 'html',
                ),
            ),
             'drop_from_enrollment_id' => 
            array (
                'name' => 'drop_from_enrollment_id',
                'vname' => 'LBL_DROP_FROM_ENROLLMENT_ID',
                'type' => 'id',
                'required'=>false,
                'reportable'=>false,
                'comment' => ''
            ),
            'payment_method' => 
            array (
                'required' => true,
                'name' => 'payment_method',
                'vname' => 'LBL_PAYMENT_METHOD',
                'type' => 'radioenum',
                'massupdate' => 0,
                'default' => 'Cash',
                'comments' => '',
                'help' => '',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'len' => 100,
                'size' => '20',
                'options' => 'menthod_payments_list',
                'studio' => 'visible',
                'dbType' => 'enum',
            ),
            'status' => 
            array (
                'required' => false,
                'name' => 'status',
                'vname' => 'LBL_STATUS',
                'type' => 'enum',
                'massupdate' => 0,
                'default' => 'Paid',
                'no_default' => false,
                'comments' => '',
                'help' => '',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => true,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'len' => 100,
                'size' => '20',
                'options' => 'status_payments_list',
                'studio' => 'visible',
                'dependency' => false,
            ),
            'card_name' => 
            array (
                'required' => false,
                'name' => 'card_name',
                'vname' => 'LBL_CARD_NAME',
                'type' => 'varchar',
                'massupdate' => 0,
                'no_default' => false,
                'comments' => '',
                'help' => '',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'len' => '255',
                'size' => '20',
            ),
            'card_type' => 
            array (
                'required' => false,
                'name' => 'card_type',
                'vname' => 'LBL_CARD_TYPE',
                'type' => 'enum',
                'massupdate' => 0,
                'default' => '',
                'no_default' => false,
                'comments' => '',
                'help' => '',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'len' => 100,
                'size' => '20',
                'options' => 'card_type_payments_list',
                'studio' => 'visible',
                'dependency' => false,
            ),
            'payment_date' => 
            array (
                'required' => true,
                'name' => 'payment_date',
                'vname' => 'LBL_PAYMENT_DATE',
                'type' => 'date',
                'massupdate' => 0,
                'no_default' => false,
                'comments' => '',
                'help' => '',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'size' => '20',
                'enable_range_search' => true,
                'options' => 'date_range_search_dom',
                'display_default' => 'now',
            ),
            'card_number' => 
            array (
                'required' => false,
                'name' => 'card_number',
                'vname' => 'LBL_CARD_NUMBER',
                'type' => 'phone',
                'dbType' => 'varchar',
                'len' => '30',
            ),
            'remain' => 
            array (
                'required' => true,
                'name' => 'remain',
                'vname' => 'LBL_REMAIN',
                'type' => 'currency',
                'massupdate' => 0,
                'no_default' => false,
                'default' => 0,
                'comments' => '',
                'help' => '',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => true,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'len' => 26,
                'size' => '20',
                'enable_range_search' => true,
                'options' => 'numeric_range_search_dom',
                'precision' => 2,
            ),
            'serial_num' => 
            array (
                'required' => false,
                'name' => 'serial_num',
                'vname' => 'LBL_SERIAL_NUM',
                'type' => 'phone',
                'dbType' => 'varchar',
                'len' => '30',
            ),
            'invoice_num' => 
            array (
                'required' => false,
                'name' => 'invoice_num',
                'vname' => 'LBL_INVOICE_NUM',
                'type' => 'phone',
                'dbType' => 'varchar',
                'len' => '30',
            ),
            'printed' => array(
                'required' => false,
                'name' => 'printed',
                'vname' => 'LBL_PRINTED',
                'type' => 'bool',
                'importable' => 'false',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
            ),
            'converted_to_revenue' => array(
                'required' => false,
                'name' => 'converted_to_revenue',
                'vname' => 'LBL_CONVERTED_TOREVENUE',
                'type' => 'bool',
                'importable' => 'false',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
            ),
            'expiration_date' => 
            array (
                'required' => false,
                'name' => 'expiration_date',
                'vname' => 'LBL_EXPIRATION_DATE',
                'type' => 'enum',
                'massupdate' => 0,
                'default' => 'January',
                'no_default' => false,
                'comments' => '',
                'help' => '',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'len' => 100,
                'size' => '20',
                'options' => 'expiration_date_payment_list',
                'studio' => 'visible',
                'dependency' => false,
            ),
            'expiration_year' => 
            array (
                'required' => false,
                'name' => 'expiration_year',
                'vname' => 'LBL_EXPIRATION_YEAR',
                'type' => 'enum',
                'massupdate' => 0,
                'default' => '2014',
                'no_default' => false,
                'comments' => '',
                'help' => '',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'len' => 100,
                'size' => '20',
                'options' => 'year_list',
                'studio' => 'visible',
                'dependency' => false,
            ),
            'card_rate' => 
            array (
                'required' => false,
                'name' => 'card_rate',
                'vname' => 'LBL_CARD_RATE',
                'type' => 'decimal',
                'len' => 5,
                'precision' => 2,
            ),
            'card_amount' => 
            array (
                'required' => false,
                'name' => 'card_amount',
                'vname' => 'LBL_CARD_AMOUNT',
                'type' => 'currency',
                'massupdate' => 0,
                'no_default' => false,
                'comments' => '',
                'help' => '',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'len' => 26,
                'size' => '20',
                'enable_range_search' => false,
                'precision' => 2,
            ),
            'customer_name' => 
            array (
                'required' => false,
                'name' => 'customer_name',
                'vname' => 'LBL_CUSTOMER_NAME',
                'type' => 'varchar',
                'massupdate' => 0,
                'no_default' => false,
                'comments' => '',
                'help' => '',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'len' => '255',
                'size' => '20',
            ),
            'company_name' => 
            array (
                'required' => false,
                'name' => 'company_name',
                'vname' => 'LBL_COMPANY_NAME',
                'type' => 'varchar',
                'massupdate' => 0,
                'no_default' => false,
                'comments' => '',
                'help' => '',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'len' => '255',
                'size' => '20',
            ),
            'amount_in_words' => 
            array (
                'required' => false,
                'name' => 'amount_in_words',
                'vname' => 'LBL_AMOUNT_IN_WORDS',
                'type' => 'varchar',
                'massupdate' => 0,
                'no_default' => false,
                'comments' => '',
                'help' => '',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'len' => '300',
                'size' => '20',
            ),
            'filename' =>
            array (
                'name' => 'filename',
                'vname' => 'LBL_FILENAME',
                'type' => 'varchar',
                'required'=>true,
                'importable' => 'required',
                'len' => '255',
                'studio' => 'false',
            ),
            'file_ext' =>
            array (
                'name' => 'file_ext',
                'vname' => 'LBL_FILE_EXTENSION',
                'type' => 'varchar',
                'len' => 100,
            ),
            'file_mime_type' =>
            array (
                'name' => 'file_mime_type',
                'vname' => 'LBL_MIME',
                'type' => 'varchar',
                'len' => '100',
            ),
            'uploadfile' =>
            array (
                'name'=>'uploadfile',
                'vname' => 'LBL_FILE_UPLOAD',
                'type' => 'file',
                'source' => 'non-db',
            ),

            //Add Field - 14/05 By Lap Nguyen 
            'loan_type' => 
            array (
                'required' => false,
                'name' => 'loan_type',
                'vname' => 'LBL_LOAN_TYPE',
                'type' => 'enum',
                'massupdate' => 0,
                'default' => '',
                'no_default' => false,
                'comments' => '',
                'help' => '',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'len' => 50,
                'size' => '20',
                'options' => 'loan_type_list',
                'studio' => 'visible',
                'dependency' => false,
            ),
            'bank_fee_rate' => 
            array (
                'required' => false,
                'name' => 'bank_fee_rate',
                'vname' => 'LBL_BANK_FEE_RATE',
                'type' => 'decimal',
                'len' => 5,
                'precision' => 2,
            ),
            'loan_fee_rate' => 
            array (
                'required' => false,
                'name' => 'loan_fee_rate',
                'vname' => 'LBL_LOAN_FEE_RATE',
                'type' => 'decimal',
                'len' => 5,
                'precision' => 2,
            ),
            'bank_fee_amount' => 
            array (
                'name' => 'bank_fee_amount',
                'vname' => 'LBL_BANK_FEE_AMOUNT',
                'type' => 'currency',
                'len' => 26,
                'precision' => 2,
            ),
            'loan_fee_amount' => 
            array (
                'name' => 'loan_fee_amount',
                'vname' => 'LBL_LOAN_FEE_AMOUNT',
                'type' => 'currency',
                'len' => 26,
                'precision' => 2,
            ),
            'bank_name' => 
            array (
                'required' => false,
                'name' => 'bank_name',
                'vname' => 'LBL_BANK_NAME',
                'type' => 'enum',
                'default' => '',
                'len' => 50,
                'size' => '20',
                'options' => 'bank_name_list',
            ),
            'payment_type' =>
            array (
                'name' => 'payment_type',
                'vname' => 'LBL_PAYMENT_TYPE',
                'type' => 'enum',
                'len' => '100',
                'default' => 'Normal',
                'options' => 'payment_type_dom',
            ),     
            'start_pay' =>
            array (
                'name' => 'start_pay',
                'vname' => 'LBL_START_PAY',
                'type' => 'date',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'size' => '20',
                'enable_range_search' => true,
                'options' => 'date_range_search_dom',
                'display_default' => '',
            ),
            'end_pay' =>
            array (
                'name' => 'end_pay',
                'vname' => 'LBL_END_PAY',
                'type' => 'date',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'size' => '20',
                'enable_range_search' => true,
                'options' => 'date_range_search_dom',
                'display_default' => '',
            ),
            'discount_in_payment' => array(
                'name' => 'discount_in_payment',
                'vname' => 'LBL_DISCOUNT_IN_PAY',
                'type' => 'currency',
                'len' => 13,
            ),
            'sponsor_amount' => array(
                'name' => 'sponsor_amount',
                'vname' => 'LBL_SPONSOR_AMOUNT',
                'type' => 'currency',
                'len' => 13,
            ),

        ),
        'relationships'=>array (
        ),
        'optimistic_locking'=>true,
        'unified_search'=>true,
    );
    if (!class_exists('VardefManager')){
        require_once('include/SugarObjects/VardefManager.php');
    }
    VardefManager::createVardef('C_Payments','C_Payments', array('basic','team_security','assignable'));