<?php
/*********************************************************************************
 * By installing or using this file, you are confirming on behalf of the entity
 * subscribed to the SugarCRM Inc. product ("Company") that Company is bound by
 * the SugarCRM Inc. Master Subscription Agreement (“MSA”), which is viewable at:
 * http://www.sugarcrm.com/master-subscription-agreement
 *
 * If Company is not bound by the MSA, then by installing or using this file
 * you are agreeing unconditionally that Company will be bound by the MSA and
 * certifying that you have authority to bind Company accordingly.
 *
 * Copyright (C) 2004-2013 SugarCRM Inc.  All rights reserved.
 ********************************************************************************/

$relationships = array (
  'c_memberships_modified_user' => 
  array (
    'id' => '2d56e1f5-4542-31c9-5351-542c4d62fe6c',
    'relationship_name' => 'c_memberships_modified_user',
    'lhs_module' => 'Users',
    'lhs_table' => 'users',
    'lhs_key' => 'id',
    'rhs_module' => 'C_Memberships',
    'rhs_table' => 'c_memberships',
    'rhs_key' => 'modified_user_id',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'c_memberships_created_by' => 
  array (
    'id' => '2d9567b7-e992-6b42-a436-542c4d630dde',
    'relationship_name' => 'c_memberships_created_by',
    'lhs_module' => 'Users',
    'lhs_table' => 'users',
    'lhs_key' => 'id',
    'rhs_module' => 'C_Memberships',
    'rhs_table' => 'c_memberships',
    'rhs_key' => 'created_by',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'c_memberships_assigned_user' => 
  array (
    'id' => '2e79c231-5ecb-9809-4c00-542c4d8fb85e',
    'relationship_name' => 'c_memberships_assigned_user',
    'lhs_module' => 'Users',
    'lhs_table' => 'users',
    'lhs_key' => 'id',
    'rhs_module' => 'C_Memberships',
    'rhs_table' => 'c_memberships',
    'rhs_key' => 'assigned_user_id',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'c_memberships_contacts_2' => 
  array (
    'id' => '9ca7dac6-d81f-3483-fb82-542c4dbb3ff1',
    'relationship_name' => 'c_memberships_contacts_2',
    'lhs_module' => 'C_Memberships',
    'lhs_table' => 'c_memberships',
    'lhs_key' => 'id',
    'rhs_module' => 'Contacts',
    'rhs_table' => 'contacts',
    'rhs_key' => 'id',
    'join_table' => 'c_memberships_contacts_2_c',
    'join_key_lhs' => 'c_memberships_contacts_2c_memberships_ida',
    'join_key_rhs' => 'c_memberships_contacts_2contacts_idb',
    'relationship_type' => 'one-to-one',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'c_printinglists_c_memberships_1' => 
  array (
    'id' => '9d0ba861-1ce7-0b78-a272-542c4d3d8442',
    'relationship_name' => 'c_printinglists_c_memberships_1',
    'lhs_module' => 'C_Printinglists',
    'lhs_table' => 'c_printinglists',
    'lhs_key' => 'id',
    'rhs_module' => 'C_Memberships',
    'rhs_table' => 'c_memberships',
    'rhs_key' => 'id',
    'join_table' => 'c_printinglists_c_memberships_1_c',
    'join_key_lhs' => 'c_printinglists_c_memberships_1c_printinglists_ida',
    'join_key_rhs' => 'c_printinglists_c_memberships_1c_memberships_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'c_memberships_leads_1' => 
  array (
    'lhs_module' => 'C_Memberships',
    'rhs_module' => 'Leads',
    'relationship_type' => 'one-to-one',
    'readonly' => true,
    'deleted' => false,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
    'relationship_name' => 'c_memberships_leads_1',
  ),
);