<?php
    /*********************************************************************************
    * By installing or using this file, you are confirming on behalf of the entity
    * subscribed to the SugarCRM Inc. product ("Company") that Company is bound by
    * the SugarCRM Inc. Master Subscription Agreement (“MSA”), which is viewable at:
    * http://www.sugarcrm.com/master-subscription-agreement
    *
    * If Company is not bound by the MSA, then by installing or using this file
    * you are agreeing unconditionally that Company will be bound by the MSA and
    * certifying that you have authority to bind Company accordingly.
    *
    * Copyright (C) 2004-2013 SugarCRM Inc.  All rights reserved.
    ********************************************************************************/

    $dictionary['C_Invoices'] = array(
        'table'=>'c_invoices',
        'audited'=>false,
        'duplicate_merge'=>true,
        'fields'=>array (
            'invoice_number' => 
            array (
                'required' => false,
                'name' => 'invoice_number',
                'vname' => 'LBL_INVOICE_NUMBER',
                'type' => 'varchar',
                'massupdate' => 0,
                'no_default' => false,
                'comments' => '',
                'help' => '',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'len' => '100',
                'size' => '20',
            ),
            'status' => 
            array (
                'required' => false,
                'name' => 'status',
                'vname' => 'LBL_STATUS',
                'type' => 'enum',
                'massupdate' => 0,
                'default' => 'Unpaid',
                'no_default' => false,
                'comments' => '',
                'help' => '',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'len' => 100,
                'size' => '20',
                'options' => 'status_invoice_list',
                'studio' => 'visible',
                'dependency' => false,
            ),
            'invoice_date' => 
            array (
                'required' => true,
                'name' => 'invoice_date',
                'vname' => 'LBL_INVOICE_DATE',
                'type' => 'date',
                'massupdate' => 0,
                'no_default' => false,
                'comments' => '',
                'help' => '',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'size' => '20',
                'enable_range_search' => true,
                'options' => 'date_range_search_dom',
                'display_default' => 'now',
            ),
            'amount' => 
            array (
                'required' => true,
                'name' => 'amount',
                'vname' => 'LBL_AMOUNT',
                'type' => 'currency',
                'massupdate' => 0,
                'no_default' => false,
                'comments' => '',
                'help' => '',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'len' => 26,
                'size' => '20',
                'enable_range_search' => true,
                'options' => 'numeric_range_search_dom',
                'precision' => 2,
            ),
            'currency_id' => 
            array (
                'required' => false,
                'name' => 'currency_id',
                'vname' => 'LBL_CURRENCY',
                'type' => 'currency_id',
                'massupdate' => 0,
                'no_default' => false,
                'comments' => '',
                'help' => '',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => 0,
                'audited' => false,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'len' => 36,
                'size' => '20',
                'dbType' => 'id',
                'studio' => 'visible',
                'function' => 
                array (
                    'name' => 'getCurrencyDropDown',
                    'returns' => 'html',
                ),
            ),
            'balance' => 
            array (
                'required' => false,
                'name' => 'balance',
                'vname' => 'LBL_BALANCE',
                'type' => 'currency',
                'massupdate' => 0,
                'no_default' => false,
                'comments' => '',
                'help' => '',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'len' => 26,
                'size' => '20',
                'enable_range_search' => true,
                'options' => 'date_range_search_dom',
                'precision' => 2,
            ),
            'payment_attempts' => 
            array (
                'required' => false,
                'name' => 'payment_attempts',
                'vname' => 'LBL_PAYMENT_ATTEMPTS',
                'type' => 'int',
                'dbType' => 'varchar',
                'len' => '5',
                'enable_range_search' => true,
                'options' => 'numeric_range_search_dom',
            ),
            'name' => 
            array (
                'name' => 'name',
                'vname' => 'LBL_NAME',
                'type' => 'name',
                'link' => true,
                'dbType' => 'varchar',
                'len' => '255',
                'unified_search' => false,
                'full_text_search' => 
                array (
                    'boost' => 3,
                ),
                'required' => false,
                'importable' => 'required',
                'duplicate_merge' => 'enabled',
                'merge_filter' => 'selected',
                'massupdate' => 0,
                'no_default' => false,
                'comments' => '',
                'help' => '',
                'duplicate_merge_dom_value' => '3',
                'audited' => false,
                'reportable' => true,
                'calculated' => false,
                'size' => '20',
            ),
            'amount_in_words' => 
            array (
                'required' => false,
                'name' => 'amount_in_words',
                'vname' => 'LBL_AMOUNT_IN_WORDS',
                'type' => 'varchar',
                'massupdate' => 0,
                'no_default' => false,
                'comments' => '',
                'help' => '',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'len' => '300',
                'size' => '20',
            ),
            'serial_num' => 
            array (
                'required' => false,
                'name' => 'serial_num',
                'vname' => 'LBL_SERIAL_NUM',
                'type' => 'phone',
                'dbType' => 'varchar',
                'len' => '30',
            ),
            'invoice_num' => 
            array (
                'required' => false,
                'name' => 'invoice_num',
                'vname' => 'LBL_INVOICE_NUM',
                'type' => 'phone',
                'dbType' => 'varchar',
                'len' => '30',
            ),
            'printed' => array(
                'required' => false,
                'name' => 'printed',
                'vname' => 'LBL_PRINTED',
                'type' => 'bool',
                'importable' => 'false',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
            ),
            //Addfield - 14/05
            'is_company' => array(
                'required' => false,
                'name' => 'is_company',
                'vname' => 'LBL_IS_COMPANY',
                'type' => 'bool',
                'importable' => 'false',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
            ),
            'company_name' => 
            array (
                'required' => false,
                'name' => 'company_name',
                'vname' => 'LBL_COMPANY_NAME',
                'type' => 'varchar',
                'len' => '100',
            ),
            'tax_code' => 
            array (
                'required' => false,
                'name' => 'tax_code',
                'vname' => 'LBL_TAX_CODE',
                'type' => 'varchar',
                'len' => '50',
            ),
            'company_address' => 
            array (
                'required' => false,
                'name' => 'company_address',
                'vname' => 'LBL_COMPANY_ADDRESS',
                'type' => 'varchar',
                'len' => '200',
            ),
            'ismoved' => array (
                'required' => false,
                'name' => 'ismoved',
                'vname' => 'LBL_ISMOVED',
                'type' => 'bool',
                'massupdate' => 0,
                'no_default' => false,
                'comments' => '',
                'help' => '',
                'importable' => 'false',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
            ),
        ),
        'relationships'=>array (
        ),
        'optimistic_locking'=>true,
        'unified_search'=>true,
    );
    if (!class_exists('VardefManager')){
        require_once('include/SugarObjects/VardefManager.php');
    }
    VardefManager::createVardef('C_Invoices','C_Invoices', array('basic','team_security','assignable'));