<?php
    $dictionary['C_Packages'] = array(
        'table'=>'c_packages',
        'audited'=>true,
        'duplicate_merge'=>true,
        'fields'=>array (
            'price' => 
            array (
                'required' => false,
                'name' => 'price',
                'vname' => 'LBL_PRICE',
                'type' => 'currency',
                'massupdate' => 0,
                'no_default' => false,
                'comments' => '',
                'help' => '',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => true,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'len' => 26,
                'size' => '20',
                'enable_range_search' => false,
                'precision' => 0,
            ),
            'currency_id' => 
            array (
                'required' => false,
                'name' => 'currency_id',
                'vname' => 'LBL_CURRENCY',
                'type' => 'currency_id',
                'massupdate' => 0,
                'no_default' => false,
                'comments' => '',
                'help' => '',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => 0,
                'audited' => false,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'len' => 36,
                'size' => '20',
                'dbType' => 'id',
                'studio' => 'visible',
                'function' => 
                array (
                    'name' => 'getCurrencyDropDown',
                    'returns' => 'html',
                ),
            ),
            'interval_package' => 
            array (
                'required' => true,
                'name' => 'interval_package',
                'vname' => 'LBL_INTERVAL_PACKAGE',
                'type' => 'enum',
                'massupdate' => 0,
                'default' => '',
                'no_default' => false,
                'comments' => '',
                'help' => '',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'len' => 100,
                'size' => '20',
                'options' => 'interval_packages_list',
                'studio' => 'visible',
                'dependency' => false,
            ),
            'package_id' => 
            array (
                'required' => false,
                'name' => 'package_id',
                'vname' => 'LBL_PACKAGE_ID',
                'type' => 'varchar',
                'massupdate' => 0,
                'no_default' => false,
                'comments' => '',
                'help' => '',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'len' => 36,
                'size' => '20',
            ),
            'number_of_payments' => 
            array (
                'name' => 'number_of_payments',
                'vname' => 'LBL_NUMBER_OF_PAYMENTS',
                'type' => 'enum',
                'comments' => '',
                'help' => '',
                'default' => '1',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'len' => 20,
                'size' => '20',
                'options' => 'number_of_payments_list',
                'studio' => 'visible',
            ),
            //Bo sung Field Kind Of Course thay the Module Program
            'kind_of_course' => 
            array (
                'name' => 'kind_of_course',
                'vname' => 'LBL_KIND_OF_COURSE',
                'type' => 'enum',
                'comments' => '',
                'help' => '',
                'default' => '',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'len' => 200,
                'size' => '20',
                'options' => 'kind_of_course_360_list',
                'studio' => 'visible',
                'required' => true,
            ),
            //END - Field Kind Of Course
            'package_type' => 
            array (
                'name' => 'package_type',
                'vname' => 'LBL_PACKAGE_TYPE',
                'type' => 'enum',
                'comments' => '',
                'help' => '',
                'default' => '',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'len' => 50,
                'size' => '20',
                'options' => 'package_type_list',
                'studio' => 'visible',
                'required' => true,
            ),
            'total_hours' => 
            array (
                'required' => true,
                'name' => 'total_hours',
                'vname' => 'LBL_TOTAL_HOURS',
                'type' => 'decimal',
                'len' => 13,
                'size' => 5,
                'precision' => '2',
                'enable_range_search' => true,
                'options' => 'numeric_range_search_dom',
            ),
            'payment_rate_1' => 
            array (
                'name' => 'payment_rate_1',
                'vname' => 'LBL_PAYMENT_PRICE_1',
                'type' => 'varchar',
                'len' => 10,
            ),
            'payment_rate_2' => 
            array (
                'name' => 'payment_rate_2',
                'vname' => 'LBL_PAYMENT_PRICE_2',
                'type' => 'varchar',
                'len' => 10,
            ),
            'payment_rate_3' => 
            array (
                'name' => 'payment_rate_3',
                'vname' => 'LBL_PAYMENT_PRICE_3',
                'type' => 'varchar',
                'len' => 10,
            ),
            'payment_rate_4' => 
            array (
                'name' => 'payment_rate_4',
                'vname' => 'LBL_PAYMENT_PRICE_4',
                'type' => 'varchar',
                'len' => 10,
            ),
            'payment_price_1' => 
            array (
                'required' => false,
                'name' => 'payment_price_1',
                'vname' => 'LBL_PAYMENT_PRICE_1',
                'type' => 'currency',
                'massupdate' => 0,
                'no_default' => false,
                'comments' => '',
                'help' => '',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'len' => 26,
                'size' => '20',
                'enable_range_search' => false,
                'precision' => 0,
            ),
            'payment_price_2' => 
            array (
                'required' => false,
                'name' => 'payment_price_2',
                'vname' => 'LBL_PAYMENT_PRICE_2',
                'type' => 'currency',
                'massupdate' => 0,
                'no_default' => false,
                'comments' => '',
                'help' => '',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'len' => 26,
                'size' => '20',
                'enable_range_search' => false,
                'precision' => 0,
            ),
            'payment_price_3' => 
            array (
                'required' => false,
                'name' => 'payment_price_3',
                'vname' => 'LBL_PAYMENT_PRICE_3',
                'type' => 'currency',
                'massupdate' => 0,
                'no_default' => false,
                'comments' => '',
                'help' => '',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'len' => 26,
                'size' => '20',
                'enable_range_search' => false,
                'precision' => 0,
            ),
            'payment_price_4' => 
            array (
                'required' => false,
                'name' => 'payment_price_4',
                'vname' => 'LBL_PAYMENT_PRICE_4',
                'type' => 'currency',
                'massupdate' => 0,
                'no_default' => false,
                'comments' => '',
                'help' => '',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'len' => 26,
                'size' => '20',
                'enable_range_search' => false,
                'precision' => 0,
            ),
            'after_discount_1' => 
            array (
                'required' => false,
                'name' => 'after_discount_1',
                'vname' => 'LBL_AFTER_DISCOUNT_1',
                'type' => 'currency',
                'massupdate' => 0,
                'no_default' => false,
                'comments' => '',
                'help' => '',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'len' => 26,
                'size' => '20',
                'enable_range_search' => false,
                'precision' => 0,
            ),
            'after_discount_2' => 
            array (
                'required' => false,
                'name' => 'after_discount_2',
                'vname' => 'LBL_AFTER_DISCOUNT_2',
                'type' => 'currency',
                'massupdate' => 0,
                'no_default' => false,
                'comments' => '',
                'help' => '',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'len' => 26,
                'size' => '20',
                'enable_range_search' => false,
                'precision' => 0,
            ),
            'after_discount_3' => 
            array (
                'required' => false,
                'name' => 'after_discount_3',
                'vname' => 'LBL_AFTER_DISCOUNT_3',
                'type' => 'currency',
                'massupdate' => 0,
                'no_default' => false,
                'comments' => '',
                'help' => '',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'len' => 26,
                'size' => '20',
                'enable_range_search' => false,
                'precision' => 0,
            ),
            'after_discount_4' => 
            array (
                'required' => false,
                'name' => 'after_discount_4',
                'vname' => 'LBL_AFTER_DISCOUNT_4',
                'type' => 'currency',
                'massupdate' => 0,
                'no_default' => false,
                'comments' => '',
                'help' => '',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'len' => 26,
                'size' => '20',
                'enable_range_search' => false,
                'precision' => 0,
            ),
            'isdiscount' => 
            array (
                'required' => false,
                'name' => 'isdiscount',
                'vname' => 'LBL_ISDISCOUNT',
                'type' => 'bool',
                'massupdate' => 0,
                'no_default' => false,
                'comments' => '',
                'help' => '',
                'importable' => 'false',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
            ),
            'discount_amount' => 
            array (
                'required' => false,
                'name' => 'discount_amount',
                'vname' => 'LBL_DISCOUNT_AMOUNT',
                'type' => 'currency',
                'massupdate' => 0,
                'no_default' => false,
                'comments' => '',
                'help' => '',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => true,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'len' => 26,
                'size' => '20',
                'enable_range_search' => false,
                'precision' => 0,
            ),
            'payment_type_1' => 
            array (
                'name' => 'payment_type_1',
                'vname' => 'LBL_PAYMENT_TYPE_1',
                'type' => 'enum',
                'default' => '',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'len' => 150,
                'size' => '20',
                'options' => 'package_payment_type_list',
                'studio' => 'visible',
            ),
            'payment_type_2' => 
            array (
                'name' => 'payment_type_2',
                'vname' => 'LBL_PAYMENT_TYPE_2',
                'type' => 'enum',
                'default' => '',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'len' => 150,
                'size' => '20',
                'options' => 'package_payment_type_list',
                'studio' => 'visible',
            ),
            'payment_type_3' => 
            array (
                'name' => 'payment_type_3',
                'vname' => 'LBL_PAYMENT_TYPE_3',
                'type' => 'enum',
                'default' => '',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'len' => 150,
                'size' => '20',
                'options' => 'package_payment_type_list',
                'studio' => 'visible',
            ),
            'payment_type_4' => 
            array (
                'name' => 'payment_type_4',
                'vname' => 'LBL_PAYMENT_TYPE_4',
                'type' => 'enum',
                'default' => '',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'len' => 150,
                'size' => '20',
                'options' => 'package_payment_type_list',
                'studio' => 'visible',
            ),
        ),    
        'relationships'=>array (
        ),
        'optimistic_locking'=>true,
        'unified_search'=>true,
    );
    if (!class_exists('VardefManager')){
        require_once('include/SugarObjects/VardefManager.php');
    }
    VardefManager::createVardef('C_Packages','C_Packages', array('basic','team_security','assignable'));