<?php
/*********************************************************************************
 * By installing or using this file, you are confirming on behalf of the entity
 * subscribed to the SugarCRM Inc. product ("Company") that Company is bound by
 * the SugarCRM Inc. Master Subscription Agreement (“MSA”), which is viewable at:
 * http://www.sugarcrm.com/master-subscription-agreement
 *
 * If Company is not bound by the MSA, then by installing or using this file
 * you are agreeing unconditionally that Company will be bound by the MSA and
 * certifying that you have authority to bind Company accordingly.
 *
 * Copyright (C) 2004-2013 SugarCRM Inc.  All rights reserved.
 ********************************************************************************/


// THIS CONTENT IS GENERATED BY MBPackage.php
$manifest = array (
  0 => 
  array (
    'acceptable_sugar_versions' => 
    array (
      0 => '',
    ),
  ),
  1 => 
  array (
    'acceptable_sugar_flavors' => 
    array (
      0 => 'PRO',
    ),
  ),
  'readme' => '',
  'key' => 'J',
  'author' => '',
  'description' => '',
  'icon' => '',
  'is_uninstallable' => true,
  'name' => 'JGradebook',
  'published_date' => '2016-05-05 08:07:54',
  'type' => 'module',
  'version' => 1462435675,
  'remove_tables' => 'prompt',
);


$installdefs = array (
  'id' => 'JGradebook',
  'beans' => 
  array (
    0 => 
    array (
      'module' => 'J_Gradebook',
      'class' => 'J_Gradebook',
      'path' => 'modules/J_Gradebook/J_Gradebook.php',
      'tab' => true,
    ),
    1 => 
    array (
      'module' => 'J_GradebookConfig',
      'class' => 'J_GradebookConfig',
      'path' => 'modules/J_GradebookConfig/J_GradebookConfig.php',
      'tab' => false,
    ),
    2 => 
    array (
      'module' => 'J_GradebookDetail',
      'class' => 'J_GradebookDetail',
      'path' => 'modules/J_GradebookDetail/J_GradebookDetail.php',
      'tab' => true,
    ),
  ),
  'layoutdefs' => 
  array (
  ),
  'relationships' => 
  array (
  ),
  'image_dir' => '<basepath>/icons',
  'copy' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/modules/J_Gradebook',
      'to' => 'modules/J_Gradebook',
    ),
    1 => 
    array (
      'from' => '<basepath>/SugarModules/modules/J_GradebookConfig',
      'to' => 'modules/J_GradebookConfig',
    ),
    2 => 
    array (
      'from' => '<basepath>/SugarModules/modules/J_GradebookDetail',
      'to' => 'modules/J_GradebookDetail',
    ),
  ),
  'language' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/language/application/en_UK.lang.php',
      'to_module' => 'application',
      'language' => 'en_UK',
    ),
    1 => 
    array (
      'from' => '<basepath>/SugarModules/language/application/en_us.lang.php',
      'to_module' => 'application',
      'language' => 'en_us',
    ),
  ),
);