<?php
    /*********************************************************************************
    * By installing or using this file, you are confirming on behalf of the entity
    * subscribed to the SugarCRM Inc. product ("Company") that Company is bound by
    * the SugarCRM Inc. Master Subscription Agreement (“MSA”), which is viewable at:
    * http://www.sugarcrm.com/master-subscription-agreement
    *
    * If Company is not bound by the MSA, then by installing or using this file
    * you are agreeing unconditionally that Company will be bound by the MSA and
    * certifying that you have authority to bind Company accordingly.
    *
    * Copyright (C) 2004-2013 SugarCRM Inc.  All rights reserved.
    ********************************************************************************/

    $dictionary['J_Inventorydetail'] = array(
        'table'=>'j_inventorydetail',
        'audited'=>false,
        'duplicate_merge'=>true,
        'fields'=>array (
            'quantity' => 
            array (
                'required' => false,
                'name' => 'quantity',
                'vname' => 'LBL_QUANTITY',
                'type' => 'int',
                'massupdate' => 0,
                'no_default' => false,
                'comments' => '',
                'help' => '',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => true,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'len' => '50',
                'size' => '20',
                'enable_range_search' => false,
                'disable_num_format' => '',
                'min' => false,
                'max' => false,
            ),
            /*'book_id' => 
            array (
                'required' => false,
                'name' => 'book_id',
                'vname' => 'LBL_BOOK_ID',
                'type' => 'text',
                'massupdate' => 0,
                'no_default' => false,
                'comments' => '',
                'help' => '',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => true,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'len' => '225',
                'size' => '20',
                'enable_range_search' => false,
                'disable_num_format' => '',
                'min' => false,
                'max' => false,
            ), */
            'remark' => 
            array (
                'required' => false,
                'name' => 'remark',
                'vname' => 'LBL_REMARK',
                'type' => 'text',
                'massupdate' => 0,
                'no_default' => false,
                'comments' => '',
                'help' => '',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => true,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'len' => '225',
                'size' => '20',
                'rows' => '3',
                'cols' => '60',
                'enable_range_search' => false,
                'disable_num_format' => '',
                'min' => false,
                'max' => false,
            ),
            'price' => 
            array (
                'required' => false,
                'name' => 'price',
                'vname' => 'LBL_PRICE',
                'type' => 'currency',
                'massupdate' => 0,
                'no_default' => false,
                'comments' => '',
                'help' => '',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => true,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'len' => 26,
                'size' => '20',
                'enable_range_search' => false,
                'precision' => 6,
            ),
            'currency_id' => 
            array (
                'required' => false,
                'name' => 'currency_id',
                'vname' => 'LBL_CURRENCY',
                'type' => 'currency_id',
                'massupdate' => 0,
                'no_default' => false,
                'comments' => '',
                'help' => '',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => 0,
                'audited' => false,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'len' => 36,
                'size' => '20',
                'dbType' => 'id',
                'studio' => 'visible',
                'function' => 
                array (
                    'name' => 'getCurrencyDropDown',
                    'returns' => 'html',
                ),
            ),
            'amount' => 
            array (
                'required' => false,
                'name' => 'amount',
                'vname' => 'LBL_AMOUNT',
                'type' => 'currency',
                'massupdate' => 0,
                'no_default' => false,
                'comments' => '',
                'help' => '',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'len' => 26,
                'size' => '20',
                'enable_range_search' => false,
                'precision' => 6,
            ),
            'inventory_name' => array(
                'required'  => false,
                'source'    => 'non-db',
                'name'      => 'inventory_name',
                'vname'     => 'LBL_LEAVING_NAME',
                'type'      => 'relate',
                'rname'     => 'name',
                'id_name'   => 'inventory_id',
                'join_name' => 'j_inventory',
                'link'      => 'j_inventory',
                'table'     => 'j_inventory',
                'isnull'    => 'true',
                'module'    => 'J_Inventory',
            ), 
            'inventory_id' => array(
                'name'              => 'inventory_id',
                'rname'             => 'id',
                'vname'             => 'LBL_LEAVING_ID',
                'type'              => 'id',
                'table'             => 'j_inventorydetail',
                'isnull'            => 'true',
                'module'            => 'J_Inventorydetail',
                'dbType'            => 'id',
                'reportable'        => false,
                'massupdate'        => false,
                'duplicate_merge'   => 'disabled',
            ), 
            'j_inventory' => array(
                'name'          => 'j_inventory',
                'type'          => 'link',
                'relationship'  => 'inventorylines',
                'module'        => 'J_Inventory',
                'bean_name'     => 'J_Inventory',
                'source'        => 'non-db',
                'vname'         => 'LBL_LEAVING_REQUEST',
            ),
            
            'book_name' => array(
                'required'  => false,
                'source'    => 'non-db',
                'name'      => 'book_name',
                'vname'     => 'LBL_BOOK_NAME',
                'type'      => 'relate',
                'rname'     => 'name',
                'id_name'   => 'book_id',
                'join_name' => 'product_templates',
                'link'      => 'book',
                'table'     => 'product_templates',
                'isnull'    => 'true',
                'module'    => 'ProductTemplates',
            ), 
            'book_id' => array(
                'name'              => 'book_id',
                'rname'             => 'id',
                'vname'             => 'LBL_BOOK_ID',
                'type'              => 'id',
                'table'             => 'product_templates',
                'isnull'            => 'true',
                'module'            => 'ProductTemplates',
                'dbType'            => 'id',
                'reportable'        => false,
                'massupdate'        => false,
                'duplicate_merge'   => 'disabled',
            ), 
            'book' => array(
                'name'          => 'book',
                'type'          => 'link',
                'relationship'  => 'inventoryline_book',
                'module'        => 'ProductTemplates',
                'bean_name'     => 'ProductTemplate',
                'source'        => 'non-db',
                'vname'         => 'LBL_PRODUCTTEMPLATE',
            ),
        ),
        'relationships'=>array (
        ),
        'optimistic_locking'=>true,
        'unified_search'=>true,
    );
    if (!class_exists('VardefManager')){
        require_once('include/SugarObjects/VardefManager.php');
    }
    VardefManager::createVardef('J_Inventorydetail','J_Inventorydetail', array('basic','team_security','assignable'));